# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build-html
      - run: npm run build-pdf
      - name: Save html artifact
        uses: actions/upload-artifact@v3
        with:
          name: html resume
          path: resume.html
      - name: Save pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf resume
          path: resume.pdf
