# this workflow builds the resume,
#  and uploads it to the GitHub release that triggered the job
#  and replaces the `index.html` file in the `cv` repository
#    (CV_REPO_TOKEN must be set in the secrets of this repository)
name: build resume and publish to GitHub release, github pages site, and gist

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build html
        run: npm run build-html
      - name: Build pdf
        run: npm run build-pdf

      - name: Save html artifact
        uses: actions/upload-artifact@v3
        with:
          name: html resume
          path: resume.html
      - name: Save pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf resume
          path: resume.pdf

  publish-release-files:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download html artifact
        uses: actions/download-artifact@v2
        with:
          name: html resume
      - name: Download pdf artifact
        uses: actions/download-artifact@v2
        with:
          name: pdf resume

      - name: Upload html to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume.html
          asset_name: resume.html
          tag: ${{ github.ref }}
          overwrite: true
          body: html resume
      - name: Upload pdf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume.pdf
          asset_name: resume.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: pdf resume

  publish-to-gh-pages-branch:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout publish branch
        uses: actions/checkout@v3
        with:
          ref: publish

      - name: Download html artifact
        uses: actions/download-artifact@v2
        with:
          name: html resume
      - name: Download pdf artifact
        uses: actions/download-artifact@v2
        with:
          name: pdf resume

      - name: Rename resume.html to index.html
        run: mv resume.html index.html
      - name: Rename resume.pdf to Alfred-Renn-CV.pdf
        run: mv resume.pdf Alfred-Renn-CV.pdf

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update resume to ${{ github.ref_name }}"

  publish-to-gist:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push json to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: resume.json
          file_type: json
