# this workflow tests the resume format, using the jsonresume schema
name: test (validate json)

on:
  push:
    paths:
      - "resume.json"
      - "validate.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
    branches: ["main"]
  pull_request:
    paths:
      - "resume.json"
      - "validate.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
